apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    io.kompose.service: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dispatch
  template:
    metadata:
      labels:
        io.kompose.service: dispatch
    spec:
      containers:
      - name: dispatch
        image: linuxacademycontent/rs-dispatch:latest
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
      restartPolicy: Always
