apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    io.kompose.service: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment
  template:
    metadata:
      labels:
        io.kompose.service: payment
    spec:
      containers:
      - name: payment
        image: linuxacademycontent/rs-payment:latest
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
      restartPolicy: Always
