apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    io.kompose.service: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ratings
  template:
    metadata:
      labels:
        io.kompose.service: ratings
    spec:
      containers:
      - name: ratings
        image: linuxacademycontent/rs-ratings:latest
        ports:
        - containerPort: 3306  # This port should be updated to match the actual port used by the ratings service
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
      restartPolicy: Always
