apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    io.kompose.service: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shipping
  template:
    metadata:
      labels:
        io.kompose.service: shipping
    spec:
      containers:
      - name: shipping
        image: linuxacademycontent/rs-shipping:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
      restartPolicy: Always
